<?php

/**
 * Neocomplexx PopUp
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php $block = $this->getLayout()->createBlock('cms/block')->setBlockId('cms_popup_newsletter_content')->toHtml(); ?>

<?php if($block): ?>

	<div id="neocomplexx_modal_newsletter" class="modal neocomplexx_modal_newsletter">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
			<div class="modal-body">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="headernewsletter-validate-detail">
					<div class="subscribe-form-content">
						<input type="text" name="email" id="newsletter" title="<?php echo $this->__('Enter your email') ?>" class="input-text required-entry validate-email" value="<?php echo $this->__('Enter your email') ?>" onfocus="if(this.value == '' || this.value == '<?php echo $this->__('Enter your email'); ?>'){ this.value = '';}" onblur="if(this.value == ''){ this.value = '<?php echo $this->__('Enter your email'); ?>';}" />
						<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
					</div>
				</form>
				<?=$block?>
			</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
	//<![CDATA[
		var headerNewsletterSubscriberFormDetail = new VarienForm('headernewsletter-validate-detail', false);
		jQuery('.header-newsletter-modal').hide();
	//]]>
	</script>

<?php endif ?>
